(module
  (type $0 (func (param i32)))
  (type $1 (func (param i32) (result i32)))
  (type $2 (func (result i32)))
  (import "spectest" "print_i32" (func $0 (type 0)))
  (func $1
    (type 1)
    (local i32 i32 i32 i32 i32 i32 i32)
    (i32.const 2)
    (local.set 2)
    (local.get 0)
    (local.set 3)
    (i32.const 8)
    (local.set 4)
    (local.get 3)
    (local.get 4)
    (i32.mul)
    (local.set 5)
    (local.get 5)
    (local.set 6)
    (local.get 2)
    (local.get 6)
    (i32.add)
    (local.set 7)
    (local.get 7)
    (local.set 1)
    (local.get 1)
    (return)
    (i32.const 0)
  )
  (func $2
    (type 2)
    (local i32 i32)
    (i32.const 5)
    (local.set 0)
    (local.get 0)
    (call 1)
    (local.set 1)
    (local.get 1)
    (call 0)
    (i32.const 6)
    (local.set 0)
    (local.get 0)
    (call 1)
    (local.set 1)
    (local.get 1)
    (call 0)
    (i32.const 7)
    (local.set 0)
    (local.get 0)
    (call 1)
    (local.set 1)
    (local.get 1)
    (call 0)
    (i32.const 8)
    (local.set 0)
    (local.get 0)
    (call 1)
    (local.set 1)
    (local.get 1)
    (call 0)
    (i32.const 0)
    (return)
    (i32.const 0)
  )
  (export "main" (func 2))
)
